const firstIntValue = 5;
const secondIntValue = 10;
const firstStringValue = 'string';
const secondStringValue = 'string two';
const boolValue = true;
const nullValue = null;
const undefinedValue = undefined;
const objectValue = {name: 'Ivan', age: 25};
const symbolValue = Symbol('!');
const otherSymbol = Symbol('#');

console.log('> and <');
console.log('Int values if 5 < 10 result: ', firstIntValue < secondIntValue);
console.log('Int values if 5 > 10 result: ', firstIntValue > secondIntValue);
console.log('String values if string < string two result: ', firstStringValue < secondStringValue);
console.log('String values if string > string two result: ', firstStringValue > secondStringValue);
console.log('Boolean values if true < false  result: ', boolValue < false);
console.log('Boolean values if true > false  result: ', boolValue > false);
console.log('Null values if null < null result: ', nullValue < null);
console.log('Null values if null > null t result: ', nullValue > null);
console.log('Undefined values if undefined < undefined result: ', undefinedValue < undefined);
console.log('Undefined values if null > null result: ', undefinedValue > undefined);
console.log('Object if {name: "Ivan", age: 25} < {name: "Ivan", age: 25}  result: ', objectValue < objectValue);
console.log('Object if {name: "Ivan", age: 25} > {name: "Ivan", age: 25}  result: ', objectValue > objectValue);
console.log('Object if {name: "Ivan"} < {name: "Ivan"} result: ', objectValue.name < objectValue.name);
console.log('Object if {name: "Ivan"} > {name: "Ivan"}  result: ', objectValue.name > objectValue.name);
console.log('Object if {age: 25} < {age: 25}  result: ', objectValue.age < objectValue.age);
console.log('Object if {age: 25} > {age: 25}  result: ', objectValue.age > objectValue.age);
console.log('Symbol values if ! < #  result: ', symbolValue.description < otherSymbol.description);
console.log('Symbol values if ! > #  result: ', symbolValue.description > otherSymbol.description);
console.log('Int and bool values if 5 < true result: ', firstIntValue < boolValue);
console.log('String and null values if string < null result: ', firstStringValue < nullValue);
console.log('Undefined and age values if undefined < object age result: ', undefinedValue < objectValue.age);
console.log('Object and age values if undefined < object age result: ', undefinedValue < objectValue.age);
console.log('Object name and symbol values if ! < Ivan age result: ', symbolValue.description < objectValue.name);

console.log('>= and <=');
console.log('Int values if 5 <= 10 result: ', firstIntValue <= secondIntValue);
console.log('Int values if 5 >= 10 result: ', firstIntValue >= secondIntValue);
console.log('String values if string <= string two result: ', firstStringValue <= secondStringValue);
console.log('String values if string >= string two result: ', firstStringValue >= secondStringValue);
console.log('Boolean values if true <= false  result: ', boolValue <= false);
console.log('Boolean values if true >= false  result: ', boolValue >= false);
console.log('Null values if null <= null result: ', nullValue <= null);
console.log('Null values if null >= null t result: ', nullValue >= null);
console.log('Undefined values if undefined <= undefined result: ', undefinedValue <= undefined);
console.log('Undefined values if null >= null result: ', undefinedValue >= undefined);
console.log('Object if {name: "Ivan", age: 25} <= {name: "Ivan", age: 25}  result: ', objectValue <= objectValue);
console.log('Object if {name: "Ivan", age: 25} >= {name: "Ivan", age: 25}  result: ', objectValue >= objectValue);
console.log('Object if {name: "Ivan"} <= {name: "Ivan"} result: ', objectValue.name <= objectValue.name);
console.log('Object if {name: "Ivan"} >= {name: "Ivan"}  result: ', objectValue.name >= objectValue.name);
console.log('Object if {age: 25} <= {age: 25}  result: ', objectValue.age <= objectValue.age);
console.log('Object if {age: 25} >= {age: 25}  result: ', objectValue.age >= objectValue.age);
console.log('Symbol values if ! <= #  result: ', symbolValue.description <= otherSymbol.description);
console.log('Symbol values if ! >= #  result: ', symbolValue.description >= otherSymbol.description);
console.log('Int and bool values if 5 <= true result: ', firstIntValue <= boolValue);
console.log('String and null values if string <= null result: ', firstStringValue <= nullValue);
console.log('Undefined and age values if undefined <= object age result: ', undefinedValue <= objectValue.age);
console.log('Object and age values if undefined <= object age result: ', undefinedValue <= objectValue.age);
console.log('Object name and symbol values if ! <= Ivan age result: ', symbolValue.description <= objectValue.name);

console.log('!=');
console.log('Int values if 5 != 10 result: ', firstIntValue != secondIntValue);
console.log('String values if string != string two result: ', firstStringValue != secondStringValue);
console.log('Boolean values if true != false  result: ', boolValue != false);
console.log('Null values if null != null result: ', nullValue != null);
console.log('Undefined values if undefined != undefined result: ', undefinedValue != undefined);
console.log('Object if {name: "Ivan", age: 25} != {name: "Ivan", age: 25}  result: ', objectValue != objectValue);
console.log('Object if {name: "Ivan"} != {name: "Ivan"} result: ', objectValue.name != objectValue.name);
console.log('Object if {age: 25} != {age: 25}  result: ', objectValue.age != objectValue.age);
console.log('Symbol values if ! != #  result: ', symbolValue.description != '#');
console.log('Int and bool values if 5 != true result: ', firstIntValue != boolValue);
console.log('String and null values if string != null result: ', firstStringValue != nullValue);
console.log('Undefined and age values if undefined != object age result: ', undefinedValue != objectValue.age);
console.log('Object and age values if undefined != object age result: ', undefinedValue != objectValue.age);
console.log('Object name and symbol values if ! != Ivan age result: ', symbolValue.description != objectValue.name);

console.log('==');
console.log('Int values if 5 == 10 result: ', firstIntValue == secondIntValue);
console.log('String values if string == string two result: ', firstStringValue == secondStringValue);
console.log('Boolean values if true == false  result: ', boolValue == false);
console.log('Null values if null == null result: ', nullValue == null);
console.log('Undefined values if undefined == undefined result: ', undefinedValue == undefined);
console.log('Object if {name: "Ivan", age: 25} == {name: "Ivan", age: 25}  result: ', objectValue == objectValue);
console.log('Object if {name: "Ivan"} == {name: "Ivan"} result: ', objectValue.name == objectValue.name);
console.log('Object if {age: 25} == {age: 25}  result: ', objectValue.age == objectValue.age);
console.log('Symbol values if ! == #  result: ', symbolValue == '#');
console.log('Int and bool values if 5 == true result: ', firstIntValue == boolValue);
console.log('String and null values if string == null result: ', firstStringValue == nullValue);
console.log('Undefined and age values if undefined == object age result: ', undefinedValue == objectValue.age);
console.log('Object and age values if undefined == object age result: ', undefinedValue == objectValue.age);
console.log('Object name and symbol values if ! == Ivan age result: ', symbolValue.description == objectValue.name);

console.log('===');
console.log('Int values if 5 === 10 result: ', firstIntValue === secondIntValue);
console.log('String values if string === string two result: ', firstStringValue === secondStringValue);
console.log('Boolean values if true === false  result: ', boolValue === false);
console.log('Null values if null === null result: ', nullValue === null);
console.log('Undefined values if undefined === undefined result: ', undefinedValue === undefined);
console.log('Object if {name: "Ivan", age: 25} === {name: "Ivan", age: 25}  result: ', objectValue === objectValue);
console.log('Object if {name: "Ivan"} === {name: "Ivan"} result: ', objectValue.name === objectValue.name);
console.log('Object if {age: 25} === {age: 25}  result: ', objectValue.age === objectValue.age);
console.log('Symbol values if ! === #  result: ', symbolValue.description === otherSymbol.description);
console.log('Int and bool values if 5 === true result: ', firstIntValue === boolValue);
console.log('String and null values if string === null result: ', firstStringValue === nullValue);
console.log('Undefined and age values if undefined === object age result: ', undefinedValue === objectValue.age);
console.log('Object and age values if undefined === object age result: ', undefinedValue === objectValue.age);
console.log('Object name and symbol values if ! === Ivan age result: ', symbolValue.description === objectValue.name);
