const FIRST_INT_VALUE = 5;
const SECOND_INT_VALUE = 10;
const FIRST_STRING_VALUE = "string";
const SECOND_STRING_VALUE = "string two";
const BOOL_VALUE = true;
const NULL_VALUE = null;
const UNDEFINED_VALUE = undefined;
const OBJECT_VALUE = {name: "Ivan", age: 25};
const SYMBOL_VALUE = Symbol('!');
const OTHER_SYMBOL = Symbol('#');

console.log('> and <');
console.log('Int values if 5 < 10 result: ', FIRST_INT_VALUE < SECOND_INT_VALUE);
console.log('Int values if 5 > 10 result: ', FIRST_INT_VALUE > SECOND_INT_VALUE);
console.log('String values if string < string two result: ', FIRST_STRING_VALUE < SECOND_STRING_VALUE);
console.log('String values if string > string two result: ', FIRST_STRING_VALUE > SECOND_STRING_VALUE);
console.log('Boolean values if true < false  result: ', BOOL_VALUE < false);
console.log('Boolean values if true > false  result: ', BOOL_VALUE > false);
console.log('Null values if null < null result: ', NULL_VALUE < null);
console.log('Null values if null > null t result: ', NULL_VALUE > null);
console.log('Undefined values if undefined < undefined result: ', UNDEFINED_VALUE < undefined);
console.log('Undefined values if null > null result: ', UNDEFINED_VALUE > undefined);
console.log('Object if {name: "Ivan", age: 25} < {name: "Ivan", age: 25}  result: ', OBJECT_VALUE < OBJECT_VALUE);
console.log('Object if {name: "Ivan", age: 25} > {name: "Ivan", age: 25}  result: ', OBJECT_VALUE > OBJECT_VALUE);
console.log('Object if {name: "Ivan"} < {name: "Ivan"} result: ', OBJECT_VALUE.name < OBJECT_VALUE.name);
console.log('Object if {name: "Ivan"} > {name: "Ivan"}  result: ', OBJECT_VALUE.name > OBJECT_VALUE.name);
console.log('Object if {age: 25} < {age: 25}  result: ', OBJECT_VALUE.age < OBJECT_VALUE.age);
console.log('Object if {age: 25} > {age: 25}  result: ', OBJECT_VALUE.age > OBJECT_VALUE.age);
console.log('Symbol values if ! < #  result: ', SYMBOL_VALUE.description < OTHER_SYMBOL.description);
console.log('Symbol values if ! > #  result: ', SYMBOL_VALUE.description > OTHER_SYMBOL.description);
console.log('Int and bool values if 5 < true result: ', FIRST_INT_VALUE < BOOL_VALUE);
console.log('String and null values if string < null result: ', FIRST_STRING_VALUE < NULL_VALUE);
console.log('Undefined and age values if undefined < object age result: ', UNDEFINED_VALUE < OBJECT_VALUE.age);
console.log('Object and age values if undefined < object age result: ', UNDEFINED_VALUE < OBJECT_VALUE.age);
console.log('Object name and symbol values if ! < Ivan age result: ', SYMBOL_VALUE.description < OBJECT_VALUE.name);

console.log('>= and <=');
console.log('Int values if 5 <= 10 result: ', FIRST_INT_VALUE <= SECOND_INT_VALUE);
console.log('Int values if 5 >= 10 result: ', FIRST_INT_VALUE >= SECOND_INT_VALUE);
console.log('String values if string <= string two result: ', FIRST_STRING_VALUE <= SECOND_STRING_VALUE);
console.log('String values if string >= string two result: ', FIRST_STRING_VALUE >= SECOND_STRING_VALUE);
console.log('Boolean values if true <= false  result: ', BOOL_VALUE <= false);
console.log('Boolean values if true >= false  result: ', BOOL_VALUE >= false);
console.log('Null values if null <= null result: ', NULL_VALUE <= null);
console.log('Null values if null >= null t result: ', NULL_VALUE >= null);
console.log('Undefined values if undefined <= undefined result: ', UNDEFINED_VALUE <= undefined);
console.log('Undefined values if null >= null result: ', UNDEFINED_VALUE >= undefined);
console.log('Object if {name: "Ivan", age: 25} <= {name: "Ivan", age: 25}  result: ', OBJECT_VALUE <= OBJECT_VALUE);
console.log('Object if {name: "Ivan", age: 25} >= {name: "Ivan", age: 25}  result: ', OBJECT_VALUE >= OBJECT_VALUE);
console.log('Object if {name: "Ivan"} <= {name: "Ivan"} result: ', OBJECT_VALUE.name <= OBJECT_VALUE.name);
console.log('Object if {name: "Ivan"} >= {name: "Ivan"}  result: ', OBJECT_VALUE.name >= OBJECT_VALUE.name);
console.log('Object if {age: 25} <= {age: 25}  result: ', OBJECT_VALUE.age <= OBJECT_VALUE.age);
console.log('Object if {age: 25} >= {age: 25}  result: ', OBJECT_VALUE.age >= OBJECT_VALUE.age);
console.log('Symbol values if ! <= #  result: ', SYMBOL_VALUE.description <= OTHER_SYMBOL.description);
console.log('Symbol values if ! >= #  result: ', SYMBOL_VALUE.description >= OTHER_SYMBOL.description);
console.log('Int and bool values if 5 <= true result: ', FIRST_INT_VALUE <= BOOL_VALUE);
console.log('String and null values if string <= null result: ', FIRST_STRING_VALUE <= NULL_VALUE);
console.log('Undefined and age values if undefined <= object age result: ', UNDEFINED_VALUE <= OBJECT_VALUE.age);
console.log('Object and age values if undefined <= object age result: ', UNDEFINED_VALUE <= OBJECT_VALUE.age);
console.log('Object name and symbol values if ! <= Ivan age result: ', SYMBOL_VALUE.description <= OBJECT_VALUE.name);

console.log('!=');
console.log('Int values if 5 != 10 result: ', FIRST_INT_VALUE != SECOND_INT_VALUE);
console.log('String values if string != string two result: ', FIRST_STRING_VALUE != SECOND_STRING_VALUE);
console.log('Boolean values if true != false  result: ', BOOL_VALUE != false);
console.log('Null values if null != null result: ', NULL_VALUE != null);
console.log('Undefined values if undefined != undefined result: ', UNDEFINED_VALUE != undefined);
console.log('Object if {name: "Ivan", age: 25} != {name: "Ivan", age: 25}  result: ', OBJECT_VALUE != OBJECT_VALUE);
console.log('Object if {name: "Ivan"} != {name: "Ivan"} result: ', OBJECT_VALUE.name != OBJECT_VALUE.name);
console.log('Object if {age: 25} != {age: 25}  result: ', OBJECT_VALUE.age != OBJECT_VALUE.age);
console.log('Symbol values if ! != #  result: ', SYMBOL_VALUE.description != '#');
console.log('Int and bool values if 5 != true result: ', FIRST_INT_VALUE != BOOL_VALUE);
console.log('String and null values if string != null result: ', FIRST_STRING_VALUE != NULL_VALUE);
console.log('Undefined and age values if undefined != object age result: ', UNDEFINED_VALUE != OBJECT_VALUE.age);
console.log('Object and age values if undefined != object age result: ', UNDEFINED_VALUE != OBJECT_VALUE.age);
console.log('Object name and symbol values if ! != Ivan age result: ', SYMBOL_VALUE.description != OBJECT_VALUE.name);

console.log('==');
console.log('Int values if 5 == 10 result: ', FIRST_INT_VALUE == SECOND_INT_VALUE);
console.log('String values if string == string two result: ', FIRST_STRING_VALUE == SECOND_STRING_VALUE);
console.log('Boolean values if true == false  result: ', BOOL_VALUE == false);
console.log('Null values if null == null result: ', NULL_VALUE == null);
console.log('Undefined values if undefined == undefined result: ', UNDEFINED_VALUE == undefined);
console.log('Object if {name: "Ivan", age: 25} == {name: "Ivan", age: 25}  result: ', OBJECT_VALUE == OBJECT_VALUE);
console.log('Object if {name: "Ivan"} == {name: "Ivan"} result: ', OBJECT_VALUE.name == OBJECT_VALUE.name);
console.log('Object if {age: 25} == {age: 25}  result: ', OBJECT_VALUE.age == OBJECT_VALUE.age);
console.log('Symbol values if ! == #  result: ', SYMBOL_VALUE == '#');
console.log('Int and bool values if 5 == true result: ', FIRST_INT_VALUE == BOOL_VALUE);
console.log('String and null values if string == null result: ', FIRST_STRING_VALUE == NULL_VALUE);
console.log('Undefined and age values if undefined == object age result: ', UNDEFINED_VALUE == OBJECT_VALUE.age);
console.log('Object and age values if undefined == object age result: ', UNDEFINED_VALUE == OBJECT_VALUE.age);
console.log('Object name and symbol values if ! == Ivan age result: ', SYMBOL_VALUE.description == OBJECT_VALUE.name);

console.log('===');
console.log('Int values if 5 === 10 result: ', FIRST_INT_VALUE === SECOND_INT_VALUE);
console.log('String values if string === string two result: ', FIRST_STRING_VALUE === SECOND_STRING_VALUE);
console.log('Boolean values if true === false  result: ', BOOL_VALUE === false);
console.log('Null values if null === null result: ', NULL_VALUE === null);
console.log('Undefined values if undefined === undefined result: ', UNDEFINED_VALUE === undefined);
console.log('Object if {name: "Ivan", age: 25} === {name: "Ivan", age: 25}  result: ', OBJECT_VALUE === OBJECT_VALUE);
console.log('Object if {name: "Ivan"} === {name: "Ivan"} result: ', OBJECT_VALUE.name === OBJECT_VALUE.name);
console.log('Object if {age: 25} === {age: 25}  result: ', OBJECT_VALUE.age === OBJECT_VALUE.age);
console.log('Symbol values if ! === #  result: ', SYMBOL_VALUE.description === OTHER_SYMBOL.description);
console.log('Int and bool values if 5 === true result: ', FIRST_INT_VALUE === BOOL_VALUE);
console.log('String and null values if string === null result: ', FIRST_STRING_VALUE === NULL_VALUE);
console.log('Undefined and age values if undefined === object age result: ', UNDEFINED_VALUE === OBJECT_VALUE.age);
console.log('Object and age values if undefined === object age result: ', UNDEFINED_VALUE === OBJECT_VALUE.age);
console.log('Object name and symbol values if ! === Ivan age result: ', SYMBOL_VALUE.description === OBJECT_VALUE.name);
